language: node_js
sudo: false
dist: trusty
cache: yarn

before_install:
  - npm install npm@latest -g

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test

notifications:
  slack: wizeline:NqBcWNFLBaluqsCWyjVNcwyh
  webhooks:
    urls:
      - https://wizeline-webhooks.appspot.com/travis/notifications
